### ISSUE TITLE
URLSearchParams is not a constructor

### ISSUE THREAD

**Issue by nczepa** [WebReflection/url-search-params#35]
Hi guys, unfortunately our shop (https://www.mytoys.de/) got an error after the last update 1 hour ago.

it seems that your last commit
https://github.com/WebReflection/url-search-params/commit/14631efa45f72c62f7aecdfcec0ab3bc36827142#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

results in an error that the constructor is not found, in our case it was like this

var URLSearchParams = require('url-search-params');
module.exports = {
var currentQuery = new URLSearchParams(window.location.search.length > 0 ? window.location.search.substr(1) : '');

**JS-ERROR in Browser console: URLSearchParams is not a constructor**

I think you couldn't see the side effects of your commit in package.json, but hopefully our feedback can help you to fix the bug in latest version 0.10.1

Greetings from Berlin

**Comment by WebReflection** [comment]
https://github.com/WebReflection/url-search-params/issues/34#issuecomment-402154909

**Comment by montogeek** [comment]
URLSearchParams is not a constructor means that your browser doesn't support it.

**Comment by WebReflection** [comment]
no @montogeek it's unfortunately a bundlers issue (apparently inherited by browserify)

**Comment by montogeek** [comment]
Yeah, I say webpack git history, it is like this since browserify times, 5 years ago.
Maybe changing webpack `target` option would fix it.

**Comment by WebReflection** [comment]
> Maybe changing webpack target option would fix it.

mind elaborating ? so I can put this on the README

**Comment by edmorley** [comment]
The default webpack `target` is "web":
https://webpack.js.org/configuration/target/

For web-like targets, the `mainFields` property defaults to `["browser", "main"]` rather than `["main"]`:
https://github.com/webpack/webpack/blob/v4.15.0/lib/WebpackOptionsDefaulter.js#L61-L66

If node projects forget to set the `target`, then they'll end up with whatever is in `browser` - but that's a configuration error on their part, not really an issue with webpack.

**Comment by WebReflection** [comment]
thanks @edmorley , I've erased the browser entry so no issue should ever happen again.
