### ISSUE TITLE
extending URL proto will fail in general

### ISSUE THREAD

**Issue by kapouer** [WebReflection/url-search-params#7]
Typically fails on safari/webkit.
You will have much better luck replacing window.URL by a custom URL that inherits and overrides
the native URL implementation.

**Comment by WebReflection** [comment]
I think I've tested it on Safari/WebKit ... are you saying the prototype is sealed?

What is failing exactly?

**Comment by WebReflection** [comment]
live test here: http://webreflection.github.io/url-search-params/test/

**Comment by WebReflection** [comment]
So the problem is not the URL, the problem is apparently `HTMLAnchorElement.prototype`

Do you have any better info about this bug? I can debug but it'll take a little while ... this is actually a regression introduced when I've decided to pollute `<a>` elements without testing WebKit and friends.

Very weird choice to have DOM prototype sealed, it's completely against polyfills :-/

**Comment by kapouer** [comment]
First, `typeof window.URL == 'object'` here, not 'function'. I suggest to just check if window.URL exists.

**Comment by WebReflection** [comment]
using possible getters to feature detect is in general like seppuku as [explained in here](https://github.com/WebReflection/url-search-params#about-htmlanchorelementprototypesearchparams), always go for `in` or, in this case, improve the test so that `/^function|object$/.test(typeof URL)` would do it.

There are way more problems than that, but I am thinking if it's worth the hassle to "fix the impossible".

I'm still trying to wrap my head around this shenanigans for a non configurable and completely screwed descriptor in WebKit. I think like I should file a bug to them instead (I will)

**Comment by WebReflection** [comment]
For the record, this is the [related WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=154458) I've just filed.

**Comment by WebReflection** [comment]
P.S. current version passes all tests that don't patch `<a>` and `URL`

**Comment by glen-84** [comment]
Is this fixed now?

**Comment by WebReflection** [comment]
Epiphany (GNOME Web), Safari, and WebKit Nightly are all green:
http://webreflection.github.io/url-search-params/test/
